select 
ORG_NAME ,
account_number, account_name,trx_date,
due_date,
trx_number,
class,
INVOICE_CURRENCY_CODE,
AMOUNT_DUE_ORIGINAL,
borc,
alacak,
borcyb,
alacakyb,
LOCATION,
REC_SIRA,
comments

,Efatura,
AltBorclu,
PSiteName

from (

SELECT 
CAST(ORG.NAME AS VARCHAR2(255)) ORG_NAME ,
C.ACCOUNT_NUMBER,
PARTY_NAME ACCOUNT_NAME,
A.TRX_DATE,
A.DUE_DATE,
A.TRX_NUMBER,
A.CLASS,
A.INVOICE_CURRENCY_CODE,
A.AMOUNT_DUE_ORIGINAL,

CASE WHEN  A.EXCHANGE_RATE_TYPE IS NOT NULL AND 
A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE>0 THEN ABS(A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE)
WHEN A.EXCHANGE_RATE_TYPE IS NULL  AND 
A.AMOUNT_DUE_ORIGINAL>0 THEN  ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END BORC,


CASE WHEN A.EXCHANGE_RATE_TYPE IS NOT NULL  AND 
A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE<0 THEN ABS(A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE)
WHEN A.EXCHANGE_RATE_TYPE IS NULL  AND 
A.AMOUNT_DUE_ORIGINAL<0 THEN  ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END ALACAK,


CASE WHEN  A.EXCHANGE_RATE_TYPE IS NOT NULL  AND 
A.AMOUNT_DUE_ORIGINAL>0 THEN ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END BORCYB,

CASE WHEN A.EXCHANGE_RATE_TYPE IS NOT NULL  AND 
A.AMOUNT_DUE_ORIGINAL<0 THEN ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END ALACAKYB
,USE.LOCATION 
, A.CUSTOMER_SITE_USE_ID
,CASE WHEN CLASS= 'INV' THEN 1 ELSE 2 END REC_SIRA
,Translate(Initcap(CASE WHEN CLASS= 'PMT' THEN 
(select min(b.comments) from  AR_CASH_RECEIPTS_ALL b  where  a.tRX_NUMBER=b.RECEIPT_NUMBER )
WHEN CLASS= 'BR' THEN
(select min(b.ATTRIBUTE15) from  RA_CUSTOMER_TRX_ALL b where  a.tRX_NUMBER=b.TRX_NUMBER)
WHEN CLASS= 'INV' OR CLASS= 'cm' OR CLASS= 'dm' THEN
(select min(b.comments) from  RA_CUSTOMER_TRX_ALL b where  a.tRX_NUMBER=b.TRX_NUMBER)
END), chr(10)||chr(11)||chr(13), '   ') comments

,CASE WHEN CLASS <> 'PMT' Then (Select MIN(trxh.ATTRIBUTE5) From RA_CUSTOMER_TRX_ALL trxh Where trxh.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID) Else '' End Efatura
,CASE WHEN CLASS <> 'PMT' Then (Select MIN(trxh.ATTRIBUTE11) From RA_CUSTOMER_TRX_ALL trxh Where trxh.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID) Else '' End AltBorclu
,CASE WHEN CLASS <> 'PMT' Then (Select MIN(partysites.PARTY_SITE_NAME) From RA_CUSTOMER_TRX_ALL trxh 
Inner Join HZ_CUST_SITE_USES_ALL siteuses 
    Inner Join HZ_CUST_ACCT_SITES_ALL siteacct
        Inner Join HZ_Party_Sites partysites
        ON partysites.PARTY_SITE_ID = siteacct.PARTY_SITE_ID
    ON siteacct.CUST_ACCT_SITE_ID = siteuses.CUST_ACCT_SITE_ID
ON trxh.BILL_TO_SITE_USE_ID = siteuses.BILL_TO_SITE_USE_ID
Where trxh.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID) Else '' End PSiteName

 FROM 
AR_PAYMENT_SCHEDULES_ALL A, 
HZ_CUST_ACCOUNTS C ,
HZ_CUST_SITE_USES_ALL USE ,
(SELECT PARTY_ID , MAX(PARTY_NAME) PARTY_NAME FROM HZ_PARTIES GROUP BY PARTY_ID ) PRT,
HR_ALL_ORGANIZATION_UNITS  ORG

WHERE 
1=1 
AND A.CUSTOMER_ID=C.CUST_ACCOUNT_ID 
AND PRT.PARTY_ID=C.PARTY_ID 
AND ORG.ORGANIZATION_ID = A.ORG_ID 
AND USE.SITE_USE_ID  =  A.CUSTOMER_SITE_USE_ID 
AND PRT.PARTY_NAME  = :P_MUSTERINAME 
AND ORG.ORGANIZATION_ID = :P_SIRKET
-- PARAMETRE EKRANINDAN SECILEN ORG. TANIMININ ID SINI GONDERIYOR !!
AND TO_DATE(TO_CHAR(A.TRX_DATE,'YYYY/MM/DD'),'YYYY/MM/DD') >= TO_DATE(TO_CHAR(:P_TARIH_START,'YYYY/MM/DD'),'YYYY/MM/DD')
AND TO_DATE(TO_CHAR(A.TRX_DATE,'YYYY/MM/DD'),'YYYY/MM/DD') <= TO_DATE(TO_CHAR(:P_TARIH_END,'YYYY/MM/DD'),'YYYY/MM/DD')

UNION ALL 

SELECT 
CAST(ORG.NAME AS VARCHAR2(255)) ORG_NAME ,
C.ACCOUNT_NUMBER,
PARTY_NAME ACCOUNT_NAME,
Max(A.TRX_DATE) trx_date ,
NULL DUE_DATE,
NULL TRX_NUMBER,
CAST('Devir ' AS CHAR(30)) CLASS,
A.INVOICE_CURRENCY_CODE,
SUM(A.AMOUNT_DUE_ORIGINAL) AMOUNT_DUE_ORIGINAL,
SUM(CASE WHEN  A.EXCHANGE_RATE_TYPE IS NOT NULL AND 
A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE>0 THEN ABS(A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE)
WHEN A.EXCHANGE_RATE_TYPE IS NULL  AND 
A.AMOUNT_DUE_ORIGINAL>0 THEN  ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END ) BORC,
SUM(CASE WHEN A.EXCHANGE_RATE_TYPE IS NOT NULL  AND 
A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE<0 THEN ABS(A.AMOUNT_DUE_ORIGINAL*EXCHANGE_RATE)
WHEN A.EXCHANGE_RATE_TYPE IS NULL  AND 
A.AMOUNT_DUE_ORIGINAL<0 THEN  ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END) ALACAK,
SUM(CASE WHEN  A.EXCHANGE_RATE_TYPE IS NOT NULL  AND 
A.AMOUNT_DUE_ORIGINAL>0 THEN ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END) BORCYB,
SUM(CASE WHEN A.EXCHANGE_RATE_TYPE IS NOT NULL  AND 
A.AMOUNT_DUE_ORIGINAL<0 THEN ABS(A.AMOUNT_DUE_ORIGINAL)
 ELSE 0 END) ALACAKYB
,USE.LOCATION 
,A.CUSTOMER_SITE_USE_ID
,0 REC_SIRA 
,Translate(Initcap(MAX(CASE WHEN CLASS= 'PMT' THEN 
(select max(b.comments) from  AR_CASH_RECEIPTS_ALL b  where  a.tRX_NUMBER=b.RECEIPT_NUMBER )
WHEN CLASS= 'BR' THEN
(select max(b.ATTRIBUTE15) from  RA_CUSTOMER_TRX_ALL b where  a.tRX_NUMBER=b.TRX_NUMBER)
WHEN CLASS= 'INV' OR CLASS= 'cm' OR CLASS= 'dm' THEN
(select max(b.comments) from  RA_CUSTOMER_TRX_ALL b where  a.tRX_NUMBER=b.TRX_NUMBER)
END)), chr(10)||chr(11)||chr(13), '   ') comments


,Max(CASE WHEN CLASS <> 'PMT' Then (Select max(trxh.ATTRIBUTE5) From RA_CUSTOMER_TRX_ALL trxh Where trxh.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID) Else '' End) Efatura
,Max(CASE WHEN CLASS <> 'PMT' Then (Select max(trxh.ATTRIBUTE11) From RA_CUSTOMER_TRX_ALL trxh Where trxh.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID) Else '' End) AltBorclu
,Max(CASE WHEN CLASS <> 'PMT' Then (Select max(partysites.PARTY_SITE_NAME) From RA_CUSTOMER_TRX_ALL trxh 
Inner Join HZ_CUST_SITE_USES_ALL siteuses 
    Inner Join HZ_CUST_ACCT_SITES_ALL siteacct
        Inner Join HZ_Party_Sites partysites
        ON partysites.PARTY_SITE_ID = siteacct.PARTY_SITE_ID
    ON siteacct.CUST_ACCT_SITE_ID = siteuses.CUST_ACCT_SITE_ID
ON trxh.BILL_TO_SITE_USE_ID = siteuses.BILL_TO_SITE_USE_ID
Where trxh.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID) Else '' End) PSiteName

FROM 
AR_PAYMENT_SCHEDULES_ALL A, 
HZ_CUST_ACCOUNTS C ,
HZ_CUST_SITE_USES_ALL USE ,
(SELECT PARTY_ID , MAX(PARTY_NAME) PARTY_NAME FROM HZ_PARTIES GROUP BY PARTY_ID ) PRT,
HR_ALL_ORGANIZATION_UNITS  ORG


WHERE 
1=1 
AND A.CUSTOMER_ID=C.CUST_ACCOUNT_ID 
AND PRT.PARTY_ID=C.PARTY_ID 
AND ORG.ORGANIZATION_ID = A.ORG_ID 
AND USE.SITE_USE_ID  =  A.CUSTOMER_SITE_USE_ID 
AND PRT.PARTY_NAME  = :P_MUSTERINAME 
AND ORG.ORGANIZATION_ID = :P_SIRKET
-- PARAMETRE EKRANINDAN SECILEN ORG. TANIMININ ID SINI GONDERIYOR !!
AND TO_DATE(TO_CHAR(A.TRX_DATE,'YYYY/MM/DD'),'YYYY/MM/DD') < TO_DATE(TO_CHAR(:P_TARIH_START,'YYYY/MM/DD'),'YYYY/MM/DD')
GROUP BY

ORG.NAME,
C.ACCOUNT_NUMBER,
PARTY_NAME,
A.INVOICE_CURRENCY_CODE,
USE.LOCATION ,
A.CUSTOMER_SITE_USE_ID
 ) 
WHERE 
1=1 
ORDER BY 
LOCATION,INVOICE_CURRENCY_CODE,trx_date,REC_SIRA