SELECT
T1.USERNAME,
perf.Display_Name,
T1.ROLE_NAME,
T1.ROLE_COMMON_NAME,
T2.SECURITYCONTEXT,
T2.SECURITYCONTEXTVALUE,
T2.CREATION_DATE
FROM
(SELECT U.USERNAME, RV.ROLE_NAME, RV.ROLE_COMMON_NAME
FROM PER_USERS U, PER_USER_ROLES UR, PER_ROLES_DN_VL RV
WHERE U.USER_ID(+) = UR.USER_ID AND UR.ROLE_ID (+) = RV.ROLE_ID AND UR.ACTIVE_FLAG = 'Y'
) T1
Left Join (SELECT  'DATA ACCESS SET' SECURITYCONTEXT, S.NAME SECURITYCONTEXTVALUE, R.ROLE_NAME, U.USERNAME, R.CREATION_DATE, R.CREATED_BY, R.LAST_UPDATE_DATE, R.LAST_UPDATED_BY
FROM FUSION.FUN_USER_ROLE_DATA_ASGNMNTS R, FUSION.GL_ACCESS_SETS S, FUSION.PER_USERS U
WHERE S.ACCESS_SET_ID = R.ACCESS_SET_ID AND U.USER_GUID = R.USER_GUID
) T2 ON T1.USERNAME = T2.USERNAME AND T1.ROLE_COMMON_NAME = T2.ROLE_NAME
Left Join PER_USERS perus
     Inner Join PER_PERSON_NAMES_F perf 
    ON perus.PERSON_ID = perf.PERSON_ID and perf.Name_Type = 'GLOBAL' and Trunc(Sysdate) between perf.EFFECTIVE_START_DATE	and perf.EFFECTIVE_END_DATE	
ON T1.USERNAME = perus.USERNAME

Where T2.SECURITYCONTEXTVALUE like 'DO%' and T2.SECURITYCONTEXTVALUE not like '%USD' 

SELECT
T1.USERNAME,
perf.Display_Name,
T1.ROLE_NAME,
T1.ROLE_COMMON_NAME,
T2.SECURITYCONTEXT,
T2.SECURITYCONTEXTVALUE,
T2.CREATION_DATE
FROM
(SELECT U.USERNAME, RV.ROLE_NAME, RV.ROLE_COMMON_NAME
FROM PER_USERS U, PER_USER_ROLES UR, PER_ROLES_DN_VL RV
WHERE U.USER_ID(+) = UR.USER_ID AND UR.ROLE_ID (+) = RV.ROLE_ID AND UR.ACTIVE_FLAG = 'Y'
) T1
Left Join (SELECT  'BUSINESS UNIT' SECURITYCONTEXT, S.NAME SECURITYCONTEXTVALUE, R.ROLE_NAME, U.USERNAME, R.CREATION_DATE, R.CREATED_BY, R.LAST_UPDATE_DATE, R.LAST_UPDATED_BY
FROM FUSION.FUN_USER_ROLE_DATA_ASGNMNTS R, FUSION.HR_ALL_ORGANIZATION_UNITS_VL S, FUSION.PER_USERS U
WHERE S.ORGANIZATION_ID = R.ORG_ID AND U.USER_GUID = R.USER_GUID
) T2
ON T1.USERNAME = T2.USERNAME AND T1.ROLE_COMMON_NAME = T2.ROLE_NAME
Left Join PER_USERS perus
     Inner Join PER_PERSON_NAMES_F perf 
    ON perus.PERSON_ID = perf.PERSON_ID and perf.Name_Type = 'GLOBAL' and Trunc(Sysdate) between perf.EFFECTIVE_START_DATE	and perf.EFFECTIVE_END_DATE	
ON T1.USERNAME = perus.USERNAME

Where T2.SECURITYCONTEXTVALUE like 'DO%' 